# [K] (c) 2020

name: TEST

on:
  push:
    branches:
      - test
    paths:
      - '.github/workflows/master.yml'

jobs:
  create:

    runs-on: ubuntu-latest
    if: github.repository == 'kongfl888/kernel-rockchip'
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: test

    - name: Set git identity
      run : |
        git config --global user.email "kongfl888@outlook.com"
        git config --global user.name "kongfl888"
    - name: Git Init
      run:  |
        git remote add rockchip https://github.com/rockchip-linux/kernel.git
        git fetch rockchip develop-4.4
        git checkout -b develop-4.4 rockchip/develop-4.4
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: develop-4.4
      run:  |
        git push --force-with-lease origin $DOWNSTREAM_BRANCH
